repos:
- repo: local
  hooks:
    - id: addlicense
      name: addlicense
      entry: addlicense
      language: system
      types: [file]
      files: \.go$
      args: ["-l", "mit", "-f", "./LICENSE", "-c", "FLYR, Inc", "**/*.go" ]
