name: License Check
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: check-license
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Setup Golang"
        uses: actions/setup-go@v5
        with:
          check-latest: false
          cache: false
          go-version-file: './go.mod'
          cache-dependency-path: './go.sum'
      - name: Install addlicense
        run: go install github.com/google/addlicense@latest
      - name: Check license headers
        run: |
          addlicense -check -l mit -f ./LICENSE -c "FLYR, Inc" **/*.go
