name: Release

on:
  workflow_dispatch: # allow a release to be triggered manually
    inputs:
      dryRun:
        description: 'Dry Run'
        required: true
        type: boolean
        default: false

jobs:
  release:
    permissions:
      contents: write # to create GitHub release (cycjimmy/semantic-release-action)
      id-token: write # to enable use of OIDC for npm provenance
      packages: write # to write to GHCR
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24.0.0
          dry_run: ${{ inputs.dryRun }}
          extra_plugins: |
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
