name: Release

on:
  workflow_dispatch: # allow a release to be triggered manually
    inputs:
      dryRun:
        description: 'Dry Run'
        required: true
        type: boolean
        default: false

jobs:
  release:
    name: Release
    uses: ./.github/workflows/semantic-release.yaml
    permissions:
      contents: write # to create GitHub release (cycjimmy/semantic-release-action)
      id-token: write # to enable use of OIDC for npm provenance
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    with:
      dryRun: ${{ inputs.dryRun || false }}
    secrets:
      FLYR_SEMANTIC_RELEASE_APP_ID: ${{ secrets.FLYR_SEMANTIC_RELEASE_APP_ID }}
      FLYR_SEMANTIC_RELEASE_PRIVATE_KEY: ${{ secrets.FLYR_SEMANTIC_RELEASE_PRIVATE_KEY }}
