name: run-gosec
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  gosec:
    name: gosec
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
