name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Setup Golang"
        uses: actions/setup-go@v5
        with:
          check-latest: false
          cache: false
          go-version-file: './go.mod'
          cache-dependency-path: './go.sum'
      - name: Test
        run: go run gotest.tools/gotestsum@latest --junitfile unit-tests.xml --format pkgname
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "unit-tests.xml"
        if: always()
